name: 27119_test

on:
  push:
    branches: [master]

jobs:
  check_test_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if test scripts exist
        run: |
          if [ ! -f "test_main.cpp" ]; then
            echo "Test script test_main.cpp not found." > error.txt
            exit 1
          fi
