name: 27119_test

#kdaj se izvede
on:
  push:
    branches: [master]

# seznam poslov
jobs:
  # preveri če obstaja test
  check_test_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if test scripts exist
        run: |
          if [ ! -f "test_main.cpp" ]; then
            echo "Test script test_main.cpp not found." > error.txt
            exit 1
          fi
      - name: Save error.txt as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: error-log
          path: error.txt

  #preveri, če obstaja error.txt. Če je bila v prejšnjem poslu napaka obstaja, drugače ne.
  prepare_and_run_tests:
    needs: [check_test_scripts]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # matrix za verzijo compilerja
        compiler: [c++11, c++17]
    if: always() && success()
    steps:
      - name: Check for error file
        run: |
          if [ -f "error.txt" ]; then
            echo "Error file found. Exiting."
            exit 1
          else
            echo "Error file not found. Proceeding with tests."
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile and run tests
      # izvede se 2x, enkrat za vsako verzijo c++ v matrix
        run: |
          g++ -std=${{ matrix.compiler }} test_main.cpp main.cpp -o test
          ./test
        working-directory: ${{ github.workspace }}