name: 27119_test

on:
  push:
    branches: [ main ]


jobs:
  check_test_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check if test scripts exist
        run: |
          if [ ! -f .tests/test_main.cpp ]; then
            echo "Test script test_main.cpp not found." > error.txt
            exit 1
          fi
